### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by onny**
Issue is fixed in latest stable nwjs release!

### CODE REVIEW

**Comment by vrutkovs** [comment]
I tried this and I still get the startup wizard, which is not really a fix

**Comment by onny** [comment]
I've made a bug report upstream here: https://github.com/nwjs/nw.js/issues/5704
Thanks for your work, it looks really intresting!

**Comment by onny** [comment]
I'm writing about that issue also here https://project-insanity.org/blog/2017/02/14/signal-messenger-standalone-fur-archlinux/

**Comment by vrutkovs** [comment]
Thanks! Updated README.md with a new issue URL

**Pull request closed without merging**
